# Generated by Django 5.1.15 on 2026-09-28 04:34

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_employeeprofile_competencies_and_more'),
        ('goals', '0001_initial'),
        ('performance', '0003_performanceimprovementplan_recognitionreward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternFeedbackReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reply_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appraisal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intern_replies', to='performance.appraisal')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_replies', to='employees.employeeprofile')),
            ],
            options={
                'verbose_name': 'Intern Feedback Reply',
                'verbose_name_plural': 'Intern Feedback Replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternGoalComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=255)),
                ('author_role', models.CharField(default='INTERN', max_length=50)),
                ('comment', models.TextField()),
                ('is_mentor', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_goal_comments', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_comments', to='goals.goal')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='intern.interngoalcomment')),
            ],
            options={
                'verbose_name': 'Intern Goal Comment',
                'verbose_name_plural': 'Intern Goal Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('TECHNICAL', 'Technical Implementation'), ('ONBOARDING', 'Onboarding & Setup'), ('DOCUMENTATION', 'Documentation & Spec'), ('EVALUATION', 'Appraisal & Review')], default='TECHNICAL', max_length=50)),
                ('instructions', models.TextField(help_text='Detailed task guidelines, acceptance criteria, and instructions from mentor.')),
                ('priority', models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], default='MEDIUM', max_length=20)),
                ('due_date', models.DateField()),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('hours_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('completion_notes', models.TextField(blank=True, default='')),
                ('artifact_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_permitted_to_complete', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_tasks', to='employees.employeeprofile')),
            ],
            options={
                'verbose_name': 'Intern Task',
                'verbose_name_plural': 'Intern Tasks',
                'ordering': ['is_completed', 'due_date', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='InternSelfAppraisalSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('self_rating', models.DecimalField(decimal_places=1, default=Decimal('8.5'), max_digits=4)),
                ('achievements', models.TextField(blank=True, default='', help_text='Key technical achievements and completed deliverables.')),
                ('challenges', models.TextField(blank=True, default='', help_text='Challenges faced and problem-solving methodology.')),
                ('skills_acquired', models.TextField(blank=True, default='', help_text='Frameworks, tools, and technical competencies developed.')),
                ('mentorship_needs', models.TextField(blank=True, default='', help_text='Areas where guidance or mentorship is requested.')),
                ('reflection_summary', models.TextField(blank=True, default='', help_text='Overall self-evaluation reflection summary.')),
                ('is_submitted', models.BooleanField(db_index=True, default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_self_appraisals', to='performance.performancecycle')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_appraisal_submissions', to='employees.employeeprofile')),
            ],
            options={
                'verbose_name': 'Intern Self-Appraisal Submission',
                'verbose_name_plural': 'Intern Self-Appraisal Submissions',
                'unique_together': {('intern', 'cycle')},
            },
        ),
    ]
