# Generated by Django 5.1.15 on 2026-09-28 08:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeeprofile_competencies_and_more'),
        ('intern', '0001_initial'),
        ('organization', '0001_initial'),
        ('performance', '0005_appraisal_allow_intern_reply_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interntask',
            name='requires_mentor_review',
            field=models.BooleanField(default=False, help_text='If true, task requires mentor review before final completion.'),
        ),
        migrations.AddField(
            model_name='interntask',
            name='review_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interntask',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interntask',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_intern_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interntask',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted for Review'), ('UNDER_REVIEW', 'Under Review'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], db_index=True, default='ASSIGNED', max_length=20),
        ),
        migrations.CreateModel(
            name='InternForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('target_role', models.CharField(default='INTERN', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('allow_draft_save', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_intern_forms', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intern_forms', to='performance.performancecycle')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intern_forms', to='organization.department')),
            ],
            options={
                'verbose_name': 'Intern Form',
                'verbose_name_plural': 'Intern Forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternFormQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('question_type', models.CharField(choices=[('TEXT', 'Single Line Text'), ('LONG_TEXT', 'Multi-line Paragraph'), ('NUMERIC', 'Numeric Input'), ('RATING', 'Rating Scale'), ('DATE', 'Date Picker'), ('CHOICE', 'Multiple Choice')], default='TEXT', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('options', models.JSONField(blank=True, default=list, help_text='List of string options for CHOICE question type.')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='intern.internform')),
            ],
            options={
                'verbose_name': 'Intern Form Question',
                'verbose_name_plural': 'Intern Form Questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternFormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_submitted', models.BooleanField(db_index=True, default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('answers', models.JSONField(default=dict, help_text='Mapping of question UUID strings to answered values.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intern_form_submissions', to='performance.performancecycle')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='intern.internform')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='employees.employeeprofile')),
            ],
            options={
                'verbose_name': 'Intern Form Submission',
                'verbose_name_plural': 'Intern Form Submissions',
                'ordering': ['-updated_at'],
                'unique_together': {('form', 'intern')},
            },
        ),
    ]
