# Generated by Django 4.2.27 on 2026-09-27 09:32

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0004_employeeprofile_competencies_and_more'),
        ('performance', '0003_performanceimprovementplan_recognitionreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalCapabilityParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(default='Technical Capability', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('benchmark_score', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Expected benchmark score out of 5.0', max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Weight in percentage', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tech_parameters', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_parameters', to='performance.performancecycle')),
            ],
            options={
                'verbose_name': 'Technical Capability Parameter',
                'verbose_name_plural': 'Technical Capability Parameters',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalCapabilityReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('mentor_assessment', models.TextField(blank=True, default='')),
                ('evidence_url', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_reviews', to='performance.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_reviews', to='employees.employeeprofile')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='performance.technicalcapabilityparameter')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_technical_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Technical Capability Review',
                'verbose_name_plural': 'Technical Capability Reviews',
                'ordering': ['parameter__name'],
                'unique_together': {('parameter', 'employee', 'cycle')},
            },
        ),
    ]
