# Generated by Django 5.1.15 on 2026-09-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_technicalcapabilityparameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='allow_intern_reply',
            field=models.BooleanField(default=True, help_text='Whether the intern can submit replies to published feedback'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='areas_for_improvement',
            field=models.JSONField(blank=True, default=list, help_text='List of actionable recommendations and growth focus areas'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='classification',
            field=models.CharField(blank=True, help_text='Published performance classification', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='recommendations',
            field=models.TextField(blank=True, help_text='Long-form development recommendations from reviewer/mentor', null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='strengths',
            field=models.JSONField(blank=True, default=list, help_text='List of key evaluated strengths and accomplishments'),
        ),
        migrations.AddField(
            model_name='performancecycle',
            name='current_phase',
            field=models.CharField(blank=True, default='Active Evaluation', help_text='Current cycle milestone phase label', max_length=50),
        ),
        migrations.AddField(
            model_name='performancecycle',
            name='evidence_deadline',
            field=models.DateField(blank=True, help_text='Cutoff date for deliverables and evidence submissions', null=True),
        ),
        migrations.AddField(
            model_name='performancecycle',
            name='self_assessment_deadline',
            field=models.DateField(blank=True, help_text='Cutoff date for intern/employee self-appraisal submissions', null=True),
        ),
    ]
